name: themovie
description: A Movie App with TMDB Movie Api.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.2.16
  hooks_riverpod: ^2.1.1
  shimmer: ^2.0.0
  go_router: ^5.2.2
  iconly: ^1.0.1
  google_fonts: ^3.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  riverpod_annotation: ^1.0.6
  dio: ^4.0.6
  dartz: ^0.10.1
  carousel_slider: ^4.1.1
  envied: ^0.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  dio_http_formatter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6
  build_runner: ^2.3.2
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo_android12.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_android12.png
    icon_background_color_dark: "#121212"

  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_android12.png"
  min_sdk_android: 21
